[general]
import = [ "~/.config/alacritty/theme.toml" ]

[window]
padding = { x = 7, y = 7}
decorations = "Buttonless"
blur = true
opacity = 0.85

[scrolling]
history = 100000

[font]
normal = { family = "JetBrainsMono NF" }
size = 14
