import = [ "~/.config/alacritty/terafox.toml" ]

[window]
padding = { x = 7, y = 7}
decorations = "Buttonless"

[scrolling]
history = 100000

[font]
normal = { family = "JetBrainsMono NF" }
size = 14
