[colors.primary]
background = '#0A0A0A'

[colors.normal]
black = '#080808'
red = '#D70000'
green = '#789978'
yellow = '#ffAA88'
blue = '#7788AA'
magenta = '#D7007D'
cyan = '#708090' 
white = '#DEEEED'
